language: python
python:
  - "2.7"

install: "pip install -r requirements.txt"

script: nosetests -v

deploy:
  provider: pypi
  user: gszathmari
  password: secret
  distributions: "sdist bdist_wheel"
  on:
    tags: true
